---
- name: template systemd service
  template: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    owner: root
    group: root
  with_items:
    - { src: etcd.j2, dest: /usr/lib/systemd/system/etcd.service }
    - { src: flanneld.j2, dest: /usr/lib/systemd/system/flanneld.service }
  tags: systemd
  notify:
    - stop and diable NetworkManager
    - enable docker
    - enable service
    - reboot

- name: copy systemd service
  copy: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    owner: root
    group: root
  with_items:
    - { src: settimezone.service, dest: /etc/systemd/system/settimezone.service }
    - { src: docker.service, dest: /usr/lib/systemd/system/docker.service }
    - { src: setup-network-environment.service, dest: /etc/systemd/system/setup-network-environment.service }
  tags: systemd
  notify:
    - stop and diable NetworkManager
    - enable docker
    - enable service
    - reboot

- name: iptables chains of nat table ACCEPT
  iptables:
    table: nat
    chain: "{{ item }}" 
    policy: ACCEPT
    state: present
  become: yes
  with_items:
    - PREROUTING
    - POSTROUTING
    - OUTPUT
  tags: iptables

- name: iptables chains ACCEPT
  iptables:
    chain: "{{ item }}"
    policy: ACCEPT
    state: present
  become: yes
  with_items:
    - INPUT
    - OUTPUT
    - FORWARD
  tags: iptables

- name: set up authorized_keys
  authorized_key:
    user: root
    state: present
    key: "{{ item }}" 
  with_file:
    - authorized_keys

