---
- name: enable service
  service: 
    name: "{{ item }}"
    enabled: yes 
    state: reloaded
  with_items:
    - etcd
    - flanneld
    - kubelet
    - setup-network-environment
    - settimezone
